version: 2

sources:
  - name: raw_circle_data
    description: raw data circle sportswear from LW
    tables:
      - name: raw_cc_stocks
        description: stock of products
      - name: raw_cc_sales
        description: sales of products
        tests: 
          - unique:
              column_name: "(product_id || '-' || date_date)"
      - name: stg_raw_circle_data__raw_cc_stocks
        description: cleaning eraw stock
        tests:
          - unique:
              column_name: product_id
      - name: int_stock_sales
        description: its a cominatond